### ISSUE TITLE
error while running examples\demo1\main2.py

### ISSUE THREAD

**Issue by ashleygrobler04** [luciasoftware/lucia#11]
Hi all, i was pulling the latest updates. i checked what has changed, and i got the following error while running examples\demo1\main2.py:
  File "C:\Users\Ashley\lucia\examples\demo1\main2.py", line 36, in <module>
    menu2.MenuItem("test", can_be_toggled=True, toggle_switch_value="Press space bar to switch", on_value="enable", off_value="disable"),
TypeError: __init__() got an unexpected keyword argument 'toggle_switch_value'

I hope this helps!

**Comment by NicklasMCHD** [comment]
Hi.
I've looked into the issue, and I'm able to reproduce it.
For some strange reason, it don't take "toggle_switch_value" even though it is a valid argument.

**Comment by kianoosh-shakeri** [comment]
@ashleygrobler04 You may git pull again. Chances are that you pulled lucia before I updated the menu2 module. Don't forget to replace lucia with your current one in the site-packages folder.

**Comment by pauliyobo** [comment]
@ashleygrobler04 are you still getting this error? if what @kianoosh-shakeri 
said works, I may as well close this issue.

**Comment by SeanTolstoyevski** [comment]
The code in the Examples folder still contains errors.

I've setup with ``pip and git``, there's nothing changing.

An error appears in the configuration of OpenAl.

I didn't understand much.

**Comment by NicklasMCHD** [comment]
hi @SeanTolstoyevski 

I think that the new commits to master should resolve the issues you're having.
Try the following:

- clone the repository.
- change into the repository directory
- run python setup.py develop

Please let me know, if that fixes the issue

**Comment by SeanTolstoyevski** [comment]
```
pip uninstall lucia
cd lucia
git fetch
python setup.py develop
```

Happy news, it works now.

but I'm still getting an error in "3d\bass_example.py".
Console error output:
```
lucia\examples\3d>python bass_example.py
Traceback (most recent call last):
  File "bass_example.py", line 16, in <module>
    player = lucia.utils.rotation.Vector()
AttributeError: module 'lucia' has no attribute 'utils'
```

Thanks for this wonderful project,
God bless you ❤😀😀.

**Comment by NicklasMCHD** [comment]
That error has been fixed in #33 and will be merged to development and soon after to master, I just need to finish up some stuff regarding that pr before I will be able to merge it.

**Comment by NicklasMCHD** [comment]
The fixes has been merged to master and a new version of lucia (v 1.1.0) has also been posted to pypi
